# Change these first
owner: bigbeartechworld # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: BigBearTechWorld
    url: https://bigbeartechworld.com
  - name: BigBearTechHub
    url: https://bigbeartechhub.com
  - name: Boxinvy
    url: https://boxinvy.com
  - name: DoorKnockerPal
    url: https://doorknockerpal.com
  - name: DoorKnockerPal Dashboard
    url: https://dashboard.doorknockerpal.com
  - name: Emailcove
    url: https://emailcove.com
  - name: Goalpense
    url: https://goalpense.bigbeartechworld.com
  - name: Mealinvy
    url: https://mealinvy.com
  - name: Panelbay
    url: https://panelbay.bigbeartechworld.com
  - name: PilotCarHub
    url: https://pilotcarhub.com
  - name: TwistedText
    url: https://twistedtext.bigbeartechworld.com
  - name: Wealtor
    url: https://wealtor.com
    
assignees: # Users to assign downtime issues (optional)
  - dragonfire1119
  
user-agent: dragonfire1119

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.bigbeartechworld.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
#   baseUrl: /uptime
  logoUrl: https://bigbeartechworld.com/cdn/local/logos/bigbearuptimev2.png?w=54
  name: BigBearUptime
  introTitle: "**BigBearUptime** is where you can see live info on all our products."
  introMessage: 
  scripts:
    - src: https://code.tidio.co/kdnp9skmyt1ojiksn9e5oe0orrw2dbpp.js
      async: true
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://bigbeartechworld.com
      
i18n:
  footer: BigBearUptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
